package vhrn

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Shell aliases are auto-edited into reversible, marker-delimited blocks so vhrn
// can regenerate or remove them cleanly without disturbing the rest of an rc file.
// `command <name>` / `\<name>` bypass the alias and reach the real binary.
const (
	aliasStart = "# >>> vhrn managed aliases >>>"
	aliasEnd   = "# <<< vhrn managed aliases <<<"
)

// aliasLine renders one alias in a shell's syntax. fish's alias takes a
// space-separated definition and appends $argv itself; bash/zsh use name=value.
func aliasLine(shell, name, target string) string {
	if shell == "fish" {
		return fmt.Sprintf("alias %s '%s'", name, target)
	}
	return fmt.Sprintf("alias %s='%s'", name, target)
}

// aliasBlock builds the managed block (markers + one alias per installed harness)
// for a shell, or "" when nothing is installed so the block is removed entirely.
func aliasBlock(hs []Harness, shell string) string {
	if len(hs) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString(aliasStart + "\n")
	b.WriteString("# Regenerated by vhrn install/uninstall; edits here are overwritten.\n")
	for _, h := range hs {
		b.WriteString(aliasLine(shell, h.Alias, "vhrn "+h.Name) + "\n")
	}
	b.WriteString(aliasEnd + "\n")
	return b.String()
}

// stripBlock removes an existing managed block (start..end inclusive) plus one
// trailing blank line, leaving other content untouched. Unchanged if absent.
func stripBlock(content string) string {
	lines := strings.Split(content, "\n")
	start, end := -1, -1
	for i, l := range lines {
		switch strings.TrimSpace(l) {
		case aliasStart:
			if start == -1 {
				start = i
			}
		case aliasEnd:
			if start != -1 && end == -1 {
				end = i
			}
		}
	}
	if start == -1 || end == -1 {
		return content
	}
	rest := append([]string{}, lines[:start]...)
	tail := lines[end+1:]
	if len(tail) > 0 && strings.TrimSpace(tail[0]) == "" {
		tail = tail[1:] // collapse the blank line the block left behind
	}
	return strings.Join(append(rest, tail...), "\n")
}

// writeAliasBlock rewrites path's managed block: strip any existing block, then
// append the fresh one (if non-empty), creating the file/dir when needed. A no-op
// when nothing changes, and it won't create an empty rc file just to remove a
// block that was never there.
func writeAliasBlock(path, block string) error {
	orig, existed := "", false
	if data, err := os.ReadFile(path); err == nil {
		orig, existed = string(data), true
	}
	content := stripBlock(orig)
	if block != "" {
		content = strings.TrimRight(content, "\n")
		if content != "" {
			content += "\n\n"
		}
		content += block
	}
	if content == orig || (!existed && content == "") {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// currentShell is the basename of $SHELL (bash/zsh/fish), or "" when unset.
func currentShell() string {
	sh := os.Getenv("SHELL")
	if sh == "" {
		return ""
	}
	return filepath.Base(sh)
}

// rcTargets returns the rc files to manage: the known-shell rc files that already
// exist, plus the current shell's (created if missing) so the alias works in the
// shell you are using now.
func rcTargets(home string) map[string]string {
	all := map[string]string{
		"bash": filepath.Join(home, ".bashrc"),
		"zsh":  filepath.Join(home, ".zshrc"),
		"fish": filepath.Join(home, ".config", "fish", "config.fish"),
	}
	targets := map[string]string{}
	for shell, path := range all {
		if fileExists(path) {
			targets[shell] = path
		}
	}
	if cur := currentShell(); cur != "" {
		if path, ok := all[cur]; ok {
			targets[cur] = path
		}
	}
	return targets
}

// syncAliases regenerates every managed alias block from the installed registry —
// the single call install and uninstall both make so the aliases always match the
// set of installed harnesses.
func syncAliases(home string) error {
	var hs []Harness
	for _, ih := range readInstalled(home) {
		if h, ok := lookupHarness(ih.Name); ok {
			hs = append(hs, h)
		}
	}
	for shell, path := range rcTargets(home) {
		if err := writeAliasBlock(path, aliasBlock(hs, shell)); err != nil {
			return err
		}
	}
	return nil
}
